#!/usr/bin/env bash
set -euo pipefail

EVOL_HOME="${EVOL_HOME:-${HOME}/.local/share/evol-dd}"
INSTALL_BIN="${HOME}/.local/bin"
EVOL_WRAPPER="${INSTALL_BIN}/evol"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

version_file() {
    local f="${REPO_ROOT}/VERSION"
    if [ -f "$f" ]; then
        head -n1 "$f" | tr -d '[:space:]'
    else
        echo "0.1.0-dev"
    fi
}

install_wrapper() {
    echo "[evol-install] Evol-DD Global Installer"
    echo "[evol-install] Target: ${EVOL_HOME}"
    echo "[evol-install] Wrapper: ${EVOL_WRAPPER}"

    if [ -L "$EVOL_WRAPPER" ]; then
        local target
        target="$(readlink -f "$EVOL_WRAPPER" 2>/dev/null || echo "")"
        if [ "$target" = "$EVOL_HOME/scripts/evol-init.sh" ]; then
            echo "[evol-install] Wrapper already installed correctly, updating..."
        else
            echo "[evol-install] Warning: existing symlink points elsewhere: $target"
            read -rp "[evol-install] Overwrite? [y/N] " confirm
            if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
                echo "[evol-install] Aborted."
                exit 0
            fi
        fi
    elif [ -f "$EVOL_WRAPPER" ]; then
        echo "[evol-install] Warning: $EVOL_WRAPPER exists and is not a symlink"
        read -rp "[evol-install] Overwrite? [y/N] " confirm
        if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
            echo "[evol-install] Aborted."
            exit 0
        fi
    fi

    mkdir -p "${INSTALL_BIN}"
    mkdir -p "${EVOL_HOME}"

    echo "[evol-install] Copying framework to ${EVOL_HOME}..."

    local exclude_patterns=(
        "--exclude=.git"
        "--exclude=.evol"
        "--exclude=.xdd"
        "--exclude=dialog"
        "--exclude=tool_result"
        "--exclude=memory"
        "--exclude=*.pyc"
        "--exclude=__pycache__"
        "--exclude=.DS_Store"
    )

    if ! command -v rsync &>/dev/null; then
        echo "[evol-install] Error: rsync not found" >&2
        exit 1
    fi

    rsync -a --delete \
        "${exclude_patterns[@]}" \
        "${REPO_ROOT}/" "${EVOL_HOME}/"

    local EVOL_VERSION_VAL
    EVOL_VERSION_VAL="$(version_file)"

    echo "[evol-install] Generating wrapper at ${EVOL_WRAPPER}..."
    local tmp_wrapper
    tmp_wrapper="$(mktemp "${EVOL_WRAPPER}.XXXXXX")"
    trap "rm -f '$tmp_wrapper'" EXIT

    cat > "$tmp_wrapper" << WRAPPER
#!/usr/bin/env bash
# Evol-DD Global Wrapper — generated by evol-global-install.sh
# Do not edit manually; re-run installer to update

EVOL_VERSION="${EVOL_VERSION_VAL}"
EVOL_HOME="\${EVOL_HOME:-\${HOME}/.local/share/evol-dd}"

get_script() {
    case "\$1" in
        doctor)  echo "\$EVOL_HOME/scripts/evol-doctor.sh" ;;
        init)    echo "\$EVOL_HOME/scripts/evol-init.sh" ;;
        gate)    echo "\$EVOL_HOME/scripts/evol-gate.py" ;;
        help|--help|"") echo "\$EVOL_HOME/scripts/evol-init.sh" ;;
        *)       echo "" ;;
    esac
}

if [ \$# -eq 0 ]; then
    exec bash "\$EVOL_HOME/scripts/evol-init.sh"
    exit 1
fi

case "\${1}" in
    --version|-v)
        echo "evol \${EVOL_VERSION}"
        exit 0
        ;;
    doctor|init|gate|help|--help)
        script="\$(get_script "\$1")"
        if [ -n "\$script" ] && [ -f "\$script" ]; then
            shift
            exec bash "\$script" "\$@"
        else
            echo "[evol] Error: framework not found at \${EVOL_HOME}" >&2
            exit 1
        fi
        ;;
    *)
        echo "[evol] Unknown command: \${1}" >&2
        echo "[evol] Run: evol help" >&2
        exit 1
        ;;
esac
WRAPPER

    chmod +x "$tmp_wrapper"
    mv -f "$tmp_wrapper" "$EVOL_WRAPPER"
    trap - EXIT

    if [ ! -x "$EVOL_WRAPPER" ]; then
        echo "[evol-install] Error: wrapper is not executable" >&2
        exit 1
    fi

    echo "[evol-install] Installed: ${EVOL_WRAPPER}"
    echo "[evol-install] Run: evol --version"
}

install_global_ide_triggers() {
    # Instala /evol como trigger global en Claude Code y OpenCode.
    # El trigger queda disponible en CUALQUIER directorio del PC,
    # igual que /anmax esta disponible globalmente en agent_anmax.
    local trigger="${EVOL_TRIGGER:-evol}"
    local workflows_dir="$REPO_ROOT/.agent/workflows"
    local count=0

    # Claude Code global: ~/.claude/commands/
    local claude_dir="$HOME/.claude/commands"
    if mkdir -p "$claude_dir" 2>/dev/null; then
        echo "[evol-install] Instalando triggers globales en Claude Code ($claude_dir)..."
        for wf in "$workflows_dir"/*.md; do
            [ -f "$wf" ] || continue
            cp "$wf" "$claude_dir/$(basename "$wf")"
            count=$((count+1))
        done
        echo "[evol-install]   $count commands → $claude_dir"
    fi

    # OpenCode global: ~/.config/opencode/command/
    local opencode_dir="$HOME/.config/opencode/command"
    if mkdir -p "$opencode_dir" 2>/dev/null; then
        echo "[evol-install] Instalando triggers globales en OpenCode ($opencode_dir)..."
        local oc_count=0
        for wf in "$workflows_dir"/*.md; do
            [ -f "$wf" ] || continue
            cp "$wf" "$opencode_dir/$(basename "$wf")"
            oc_count=$((oc_count+1))
        done
        echo "[evol-install]   $oc_count commands → $opencode_dir"
    fi

    # Codex global: ~/.codex/skills/ (ya lo hace evol-adapt codex)
    if command -v bash >/dev/null 2>&1 && [ -f "$REPO_ROOT/scripts/evol-adapt.sh" ]; then
        echo "[evol-install] Instalando Codex global orchestrator..."
        bash "$REPO_ROOT/scripts/evol-adapt.sh" codex 2>/dev/null || true
    fi

    echo "[evol-install] Triggers globales instalados. Abrir cualquier carpeta en Claude Code u OpenCode — /${trigger} disponible."
}

if [ "${1:-}" = "--self-install" ]; then
    install_wrapper
    install_global_ide_triggers
elif [ "${1:-}" = "--install-triggers" ]; then
    # Solo instalar triggers (util para actualizar sin reinstalar todo)
    install_global_ide_triggers
else
    echo "Usage:"
    echo "  bash scripts/evol-global-install.sh --self-install       # instala CLI + triggers globales"
    echo "  bash scripts/evol-global-install.sh --install-triggers   # solo actualiza triggers IDE globales"
    exit 1
fi